### ISSUE TITLE
MLC Model flag

### ISSUE THREAD

**Issue by crcrewso** [esimiele/VMAT-TBI#1]
### Documentation Bug:
In the configuration file the variable MLC model actually corresponds to the machine's MLC ID. As such this will be unique per machine. 

### Question:
To support multiple Linacs how does one specify different MLC's for different machines with your GUI and config file?

**Comment by esimiele** [comment]
Sorry for the slow response. Been super busy clinically and studying for ABR part 3. Good catch. If the wrong MLC model is specified, then the plan will not optimize and the executable will crash. The plug-in script should run fine. The MLC model ID is used when the method 'OptimizeVMAT' is called from the progressWindow class. I elected to specify optimization options as an argument to this method (to control the intermediate dose option). However, the the constructor for the OptimizationOptionsVMAT class that has the intermediate dose option as an argument also requires the MLC model ID.  When I wrote the code, we used two linacs for VMAT TBI treatment, both of which were matched machines that used the same MLC model. So, this is a section of the code I wrote and forgot about since it wasn't an issue for us.

Looking back at the ESAPI documentation, it appears that you can leave the MLC model ID blank if there is only one MLC model configured for the selected linac (which is pretty typical). I've revised the code in the winter2021_beta branch to incorporate this change and tested it on v16 of Eclipse (it should also work on v15). You no longer need to specify the MLC model in the configuration file. The code should automatically select the appropriate MLC to add to each field for optimization regardless of what linac has been chosen for planning.

Let me know if this fixes the issue.

**Comment by crcrewso** [comment]
Thank you, that looks great, will test shortly.
