### ISSUE TITLE
Error report regarding Async 

### ISSUE THREAD

**Issue by Erhushenshou** [esimiele/VMAT-TBI#16]
I am using async in my tbi program as you do. But it always reported an errror: Atomic access violation. Do you know how I can figure this out? Once I cancelled the async and gave up outputting message in the block, it worked without reporting this problem.

**Comment by esimiele** [comment]
I'm not familiar with this error, but I'm guessing a thread on your program is trying to access something that doesn't belong to it. I believe my code uses a combination of async and threading. I remember this being very tricky to get right when initially writing the code as the exception codes are not super helpful in identifying the offending piece of code. In fact, most of the time the program would simply crash and would report no error at all haha. In my case, it was trial and error to find the correct syntax (due to my lack of experience with threading). Unless you post/upload your code, I really can't help much more than that.

**Comment by crcrewso** [comment]
> I am using async in my tbi program as you do. But it always reported an errror: Atomic access violation. Do you know how I can figure this out? Once I cancelled the async and gave up outputting message in the block, it worked without reporting this problem.

I'm very curious about your problem, could you provide some details about the system you're using to compile the code and the system you're using to run the two scripts? Is this all Citrix? Is this all from the same Eclipse planning workstation? Is there a third machine involved?

**Comment by esimiele** [comment]
Closing this issue as resolved due to no communication for 2 months
