### ISSUE TITLE
Discussion: Refactor request

### ISSUE THREAD

**Issue by crcrewso** [esimiele/VMAT-TBI#2]
For multi-site deployment it would be great if the file paths could be moved to a configuration file. 
I'm not sure if it makes sense to use the existing configuration file or to create a second one that won't show up when the user goes to view the configuration window.

**Comment by esimiele** [comment]
Agreed for sure. This is something I've struggled with for awhile. You've seen that two configuration files are currently required, one for the plug-in and one for the executable, even though they contain the same information. The reason for this is because, when I wrote the code, my institution did not allow un-verified executables to run on the hospital file server. The only way to run the executable was through visual studio on the T-box or if the executable was dropped on a thick client desktop. Thus, the plug-in and executable are located in two different spots and the only way for them to reference a common configuration file would be to hard-code the location of the configuration file on each institutions file server (something the user would have to do). 

Since most hospitals don't allow users to install applications on the file server, there isn't a way to setup a common location for the scripts on all hospital systems. I'm open to suggestions on how to fix this as I would really like to unify the configuration settings so only one file is referenced. In addition, I would like for minimal intervention on the user's part to set this up (i.e., I'd like to avoid having them hard-code the location into the program).

Let me know. Thanks!

**Comment by crcrewso** [comment]
I can see where those restrictions come from. Right now I have the exe, the dll, and the script all sitting in the default folder for scripting on the storage server. Then on the Citrix desktop of our test eclipse environment I have a shortcut. It's not ideal and I have to think about it further but with this configuration I only have one configuration file. I have not thought to try running the program from a non-osp enabled workstation.

**Comment by crcrewso** [comment]
Update, Requires OSP, and most likely full eclipse locally for the correct SDK to be accessible to the script

**Comment by esimiele** [comment]
I'm working on this issue. You can see the direction I'm going on the alpha branch of the code. Everything is being converted to executables and unified under one directory so you should only have to keep track on one folder of information. I'm at the stage of testing now. First, running everything via citrix then I'll work on running everything locally if the computer has Aria installed. I'll post my progress on the alpha branch. Also feel free to fork that branch of the code, implement your own solutions , and open a pull request. I'd be interested to see what you come up with.

**Comment by esimiele** [comment]
This has been fixed in the soon to be released VMAT-TBI-CSI autoplanning code. Stay tuned
