### ISSUE TITLE
cannot access the log file

### ISSUE THREAD

**Issue by JasonY-Web** [esimiele/VMAT-TBI#31]
I am trying my first case (not sample patient) and got a few times the same error from the executable: 
        _The process cannot access the log file (patientID.txt) because it is being used by another process._  
That last time it started the optimization at 6:15am, after 3rd iterations it was able to write to the log file at 10:03am, then it complains that the file is not accessible at sometime before 10:20am. Pretty sure no one is touching the log file.

The only thing I can think of is maybe it's expecting to access the file in some milliseconds but did not get response quick enough? My files are in a network drive with a bit long path. Thanks.

**Comment by esimiele** [comment]
Interesting. I haven't seen this error come up before (other than when someone is explicitly messing with the log file). Does it throw this error when planning the sample cases? If not, that's interesting. If yes, then it might be because of your theory. A simple check would be to change the log file path to a local directory on the computer running the optimization loop. If you don't get the error, then it might be due to trying to access the network drive. If you do get the error on a local drive, we'll have to dig a bit deeper to find the error. To prevent the script from crashing, replace line 687 in VMATTBI_optLoopMT/progressWindow.xaml.cs with:

try
{
File.AppendAllText(fileName, output);
}
catch(Exception e)
{
provideUpdate("Error! Cannot write to log file!");
provideUpdate(e.Message);
provideUpdate(e.StackTrace);
}

Then recompile and try again. If the script can't write to the file it will print a big long error message to the progress window, but it should keep going. Let me know what you find.

**Comment by JasonY-Web** [comment]
I copied all the files to a local C drive, so far the error has not coming up yet. While a day ago it appeared at least 2-3 times. I assume it is because of accessing the network drive files and our hospital network often has hiccups.  I assume it is solved, if not, I will report it here again. Thank you for very prompt answering.

**Comment by esimiele** [comment]
Sounds good. Keep me posted on what happens. I'll leave this issue open until you confirm it was a network drive issue

**Comment by esimiele** [comment]
Assuming this issue is resolved. Closing
