### ISSUE TITLE
Dose rate 600 MU/min?

### ISSUE THREAD

**Issue by JasonY-Web** [esimiele/VMAT-TBI#32]
I read your PPT presentation "VMAT TBI: Stanford Experience" by Nataliya in 2021 saying that "Dose rate at 100-200 MU/min for Head/Chest iso to keep average dose rate <20 cGy/min for lungs", but it looks like your script beam placement set all dose rate to 600 MU/min? That not only does not keep the dose rate to lung <20Gy/min, but also totally change how the optimizer works. 

What is your current practice for the dose rate for the VMAT plan?  You keep low dose rate for only the lung beams, or all the VMAT beams? thanks.

**Comment by esimiele** [comment]
Yes, the script places all beams with a dose rate of 600 MU/min. Something we said in the presentation that wasn't written on the slides was we place all beams with 600 MU/min dose rate and optimize with 600 MU/min, but once we have a final plan, we then calculate the mean dose rate to the lungs based on the final mean dose to the lungs and the approximate time to deliver that dose (e.g., number of beams that intercept the lungs * 1 min). Based on that calculated dose rate, we then adjust the maximum MU rate for each beam that intercepts the lungs to lower the average dose rate to 20 cGy/min. It usually results in lowering the dose rate to 100-200 MU/min. All other beams have the max dose rate of 600 MU/min (we don't want delivery to take forever haha).

We chose to do it this way rather than starting off by placing the beams with a dose rate of 100 MU/min as this limits the maximum dose rate for that field to 100 MU/min even though it may not be necessary for each patient. 

Of course, one potential limitation of this method is that you might end up in a situation where the MU per control point, gantry speed, etc. is not physically achievable. Which is why IMRT QA is super important for this method (with the dose rate adjusted for the relevant beams). However, we have treated > 80 patients at Stanford using this method and have not run into this issue yet (I'm guessing the MU/control point is already so low that lowering the max dose rate for these beams doesn't have a huge impact). If you're uncomfortable with this method, you can manually change the dose rate for all chest fields to 100 MU/min prior to optimization (should only take a moment in Eclipse).

**Comment by JasonY-Web** [comment]
Ahh, that makes good sense. Good to know that the VMAT beam dose rate can change from 600 to 100-200 yet still maintain the delivery ability without re-optimize the control-point based (not fluence-based) delivery. Maybe downsizing the dose rate is never an issue to the physical limitation of the machine or MLC leaves, etc., because they all just become slower. Thank you very much for the detailed explanations!

**Comment by esimiele** [comment]
No problem. If you run into any more issues with dose rate or you're finding that the plans are undeliverable after scaling, let me know and we can revisit this question. Otherwise, I'll close this issue.
