### ISSUE TITLE
Dose not being calculated on AP/PA plans

### ISSUE THREAD

**Issue by adamblais** [esimiele/VMAT-TBI#37]
First off, thank you for sharing these scripts. They are truly impressive!

After running the script, I noticed that the dose is not calculated on the AP/PA plans. I'm not sure if this is the intended function? I couldn't find much on this in the documentation.

The VMAT plan looks great, but when I calculate the AP/PA dose, those junctions are not very smooth. Is this normal? Perhaps this is just the junction geometry of static beams, but thought I would ask.

**Comment by esimiele** [comment]
Haha thank you for the kind words! 
Dose is not calculated for the AP/PA plans because it is intended for the user to manually plan a FiF plan for the legs. That functionality is not yet included in the code. 
Sorry it's not more explicitly mentioned in the documentation. The junctions are likely terrible since there is no modulation by the MLCs on the plan produced by the code. Our general workflow is to take the AP/PA plan produced by the code and make a crude FiF plan (doesn't have to be polished), set the AP/PA plan as a base dose plan, optimize the VMAT plan, refine the AP/PA FiF plan once you are happy with the VMAT plan. Thanks for confirming!

Edit: Also, feel free to have a look at the updated autoplanning code (which includes VMAT CSI in addition to VMAT TBI) as the code in this repo will be deprecated in the future: https://github.com/esimiele/VMAT-TBI-CSI

**Comment by adamblais** [comment]
That clears things up, thank you!
