### ISSUE TITLE
Bug: Acuros

### ISSUE THREAD

**Issue by crcrewso** [esimiele/VMAT-TBI#4]
Will debug further as time allows

When trying to calculate in V15.6 with Acuros the exe crashes instead of failing gracefully or handling error notifications.

**Comment by esimiele** [comment]
Interesting. Unfortunately, this is a product of my inexperience in error handling with multithreading. This is something I'm working on so the code won't freak out if it runs into a problem (I'm guessing the executable just closed completely with no warning at all?). 
Would you mind sending me the log file for this run (anonymized of course)? This would give me a better idea of when it crashed and what the issue might be.

**Comment by crcrewso** [comment]
I've done some more digging. 2 notes that mean Acuros support might not be warranted or required. I was able to use the Eclipse Optimizer directly with Acuros to see some of the errors, and a couple other issues showed up. 
- The maximum grid size of 0.3 cm is too small, adding time to the calculation
- GPU support isn't feasable with our FAS GPU's as there are out of memory issues.

**Comment by esimiele** [comment]
For the majority of users, GPU/Acuros support isn't feasible due to current computing limitations. However, there is at least one group that uses these features (a children's hospital), so I'll leave this feature in for now. I've added some code to the latest version of the 'beta' branch that should handle errors in the optimization loop gracefully rather than crashing the entire program. So even if these options are ticked, it shouldn't result in a crash and burn of the executable.
