### ISSUE TITLE
Some error reported, let's see what's wrong.

### ISSUE THREAD

**Issue by Erhushenshou** [esimiele/VMAT-TBI#9]
Sometimes in the first step it would report an error that len stucture is high resolution and reported like below:
![image](https://user-images.githubusercontent.com/38848249/165518300-2a94817c-2eb9-4909-a360-2fd8150e92b6.png)
In the last step of optimization, it will report:
![image](https://user-images.githubusercontent.com/38848249/165518434-9619b07e-0b8b-4d34-a9bc-58d6bbaf7d8c.png)
If we don't click on ok, it will not proceed which decrease efficiency.
So why it would report this warning? Could you fix to automatically proceed so that we could throw it away and do other things? Another suggestion is that provding a save button in the UI that we can save and exit otherwise we ended up getting nothing. Thank you.

**Comment by esimiele** [comment]
First error: Can you send me the entire error message? I can't see what line it's failing at. Also can you send me a screenshot of the structure names? The code assumes the max length of any structure name is 16 characters, which becomes important when naming newly created low resolution structures.

Second error: This is an Eclipse warning, not a warning thrown by the script. It's not something the script can control (it's the same error message reported in the calculation window within Eclipse when you manually perform dose calculations). This is something I was working on shortly before leaving Stanford. Unfortunately, it was a difficult error to reproduce, which made it tough to test code that would fix it. I welcome any suggestions on how to fix this. My approach was using libraries that could be used to see what windows were open and in focus. If the window had no name or the text contained in the window was similar to other Eclipse error messages, the code would send the command to close the window so the calculation could continue. Unfortunately, I didn't have enough time to get it working since it was a tough error to consistently produce. 

Good idea. I'll incorporate that change into the beta branch soon.

**Comment by Erhushenshou** [comment]
I would klike to suggest escape warning otherwise I would have to click OK to proceed calculation. I prefer leaving it alone and check after all calculation is done.

**Comment by Erhushenshou** [comment]
By the way, could you provide an sop of your TBI procedure for us to refer to? we are now establishing our own.

**Comment by esimiele** [comment]
I agree. Unfortunately, I didn't have enough time to implement a fix while at Stanford, but is something I'm working on now. Others have reported similar issues with automation in scripting. 
E.g., see: https://www.reddit.com/r/esapi/comments/umzp7j/prevent_warning_dialogues_when_using_calculatedose/
I'll work on implementing a similar solution proposed by Dr. Carden when I get a chance.

Sure, here are two good references from our group explaining the scripting and the technique itself:
https://pubmed.ncbi.nlm.nih.gov/33711488/
https://www.sciencedirect.com/science/article/abs/pii/S1879850021003507
